## Numpy

In [2]:
import numpy as np
from numpy import linalg as la

In [3]:
A1=np.array([5,7])
A2=np.array([[6,1],[2,8]])
A3=np.array([[[4,3],[2,9]]])
A4=np.array([[[[7,3],[6,6]]]])
A5=np.array([[[[[3,3],[9,6]]]]])

In [4]:
print(A1)
print(A2)
print(A3)
print(A4)
print(A5)

[5 7]
[[6 1]
 [2 8]]
[[[4 3]
  [2 9]]]
[[[[7 3]
   [6 6]]]]
[[[[[3 3]
    [9 6]]]]]


In [5]:
print(la.det(A2))

46.0


In [6]:
print(la.det(A3))

[30.]


In [7]:
print(la.det(A4))

[[24.]]


In [8]:
print(la.det(A5))

[[[-9.]]]


In [9]:
print(la.inv(A2))

[[ 0.17391304 -0.02173913]
 [-0.04347826  0.13043478]]


In [10]:
print(la.inv(A3))

[[[ 0.3        -0.1       ]
  [-0.06666667  0.13333333]]]


In [11]:
print(la.inv(A4))

[[[[ 0.25       -0.125     ]
   [-0.25        0.29166667]]]]


In [12]:
print(la.inv(A5))

[[[[[-0.66666667  0.33333333]
    [ 1.         -0.33333333]]]]]


In [13]:
print(la.matrix_rank(A1))

1


In [14]:
print(la.matrix_rank(A2))

2


In [15]:
print(la.matrix_rank(A3))

[2]


In [16]:
print(la.matrix_rank(A4))

[[2]]


In [17]:
print(la.matrix_rank(A5))

[[[2]]]


In [18]:
print(np.trace(A2))

14


In [19]:
print(np.trace(A3))

[4 3]


In [20]:
print(np.trace(A4))

[[7 3]
 [6 6]]


In [21]:
print(np.trace(A5))

[[[3 3]
  [9 6]]]


In [22]:
print(np.diag(A1))

[[5 0]
 [0 7]]


In [23]:
print(np.diag(A2))

[6 8]


In [24]:
x,y=la.eig(A2)
print("Vectors:",y)

Vectors: [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [25]:
x,y=la.eig(A3)
print("Vectors:",y)

Vectors: [[[-0.9486833  -0.4472136 ]
  [ 0.31622777 -0.89442719]]]


In [26]:
_,y=la.eig(A4)
print("Vectors:",y)

Vectors: [[[[ 0.62246561 -0.53222953]
   [ 0.78264715  0.8466001 ]]]]


In [27]:
x,y=la.eig(A5)
print("Roots:",x)
print("Vectors:",y)

Roots: [[[[-0.90832691  9.90832691]]]]
Vectors: [[[[[-0.60889368 -0.3983218 ]
    [ 0.79325185 -0.91724574]]]]]


In [28]:
print(la.eigvals(A2))

[5.26794919 8.73205081]


In [29]:
print(la.eigvals(A3))

[[ 3. 10.]]


In [30]:
print(la.eigvals(A4))

[[[10.77200187  2.22799813]]]


In [31]:
print(la.eigvals(A5))

[[[[-0.90832691  9.90832691]]]]


## Pandas

## Data1

In [35]:
import pandas as pd
data=pd.read_csv(r"C:\Users\kyathi\Downloads\1_2015.csv")
data.describe()




Happiness Rank  Happiness Score  Standard Error  \
count      158.000000       158.000000      158.000000   
mean        79.493671         5.375734        0.047885   
std         45.754363         1.145010        0.017146   
min          1.000000         2.839000        0.018480   
25%         40.250000         4.526000        0.037268   
50%         79.500000         5.232500        0.043940   
75%        118.750000         6.243750        0.052300   
max        158.000000         7.587000        0.136930   

       Economy (GDP per Capita)      Family  Health (Life Expectancy)  \
count                158.000000  158.000000                158.000000   
mean                   0.846137    0.991046                  0.630259   
std                    0.403121    0.272369                  0.247078   
min                    0.000000    0.000000                  0.000000   
25%                    0.545808    0.856823                  0.439185   
50%                    0.910245    1.029510                  0.696705   
75%                    1.158448    1.214405                  0.811013   
max                    1.690420    1.402230                  1.025250   

          Freedom  Trust (Government Corruption)  Generosity  \
count  158.000000                     158.000000  158.000000   
mean     0.428615                       0.143422    0.237296   
std      0.150693                       0.120034    0.126685   
min      0.000000                       0.000000    0.000000   
25%      0.328330                       0.061675    0.150553   
50%      0.435515                       0.107220    0.216130   
75%      0.549092                       0.180255    0.309883   
max      0.669730                       0.551910    0.795880   

       Dystopia Residual  
count         158.000000  
mean            2.098977  
std             0.553550  
min             0.328580  
25%             1.759410  
50%             2.095415  
75%             2.462415  
max             3.602140

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        158 non-null    object 
 1   Region                         158 non-null    object 
 2   Happiness Rank                 158 non-null    int64  
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 1

In [37]:
print("\nSum:\n",data.sum())


Sum:
 Country                          SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...
Region                           Western EuropeWestern EuropeWestern EuropeWest...
Happiness Rank                                                               12560
Happiness Score                                                            849.366
Standard Error                                                             7.56579
Economy (GDP per Capita)                                                 133.68968
Family                                                                   156.58526
Health (Life Expectancy)                                                  99.58098
Freedom                                                                   67.72116
Trust (Government Corruption)                                             22.66065
Generosity                                                                37.49269
Dystopia Residual                                                        331.638

In [38]:
print("\nCummulative sum\n:",data.cumsum())


Cummulative sum
:                                                Country  \
0                                          Switzerland   
1                                   SwitzerlandIceland   
2                            SwitzerlandIcelandDenmark   
3                      SwitzerlandIcelandDenmarkNorway   
4                SwitzerlandIcelandDenmarkNorwayCanada   
..                                                 ...   
153  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
154  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
155  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
156  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   
157  SwitzerlandIcelandDenmarkNorwayCanadaFinlandNe...   

                                                Region  Happiness Rank  \
0                                       Western Europe               1   
1                         Western EuropeWestern Europe               3   
2           Western EuropeWestern EuropeWestern Europe        

In [39]:
print("\nCount:\n",data.count())



Count:
 Country                          158
Region                           158
Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64


In [40]:
print("\nMax:\n",data.max())



Max:
 Country                                Zimbabwe
Region                           Western Europe
Happiness Rank                              158
Happiness Score                           7.587
Standard Error                          0.13693
Economy (GDP per Capita)                1.69042
Family                                  1.40223
Health (Life Expectancy)                1.02525
Freedom                                 0.66973
Trust (Government Corruption)           0.55191
Generosity                              0.79588
Dystopia Residual                       3.60214
dtype: object


In [41]:
print("\nMin:\n",data.min())


Min:
 Country                                        Afghanistan
Region                           Australia and New Zealand
Happiness Rank                                           1
Happiness Score                                      2.839
Standard Error                                     0.01848
Economy (GDP per Capita)                               0.0
Family                                                 0.0
Health (Life Expectancy)                               0.0
Freedom                                                0.0
Trust (Government Corruption)                          0.0
Generosity                                             0.0
Dystopia Residual                                  0.32858
dtype: object


In [42]:
data.head()

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  Dystopia Residual  
0     0.29678            2.51738  
1     0.43630            2.70201  
2     0.34139            2.49204  
3     0.34699            2.46531  
4     0.45811            2.45176

In [43]:
data.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [44]:
new_data = data.drop(["Country","Region"],axis=1)

In [45]:
print("\nMean:\n",new_data.mean())


Mean:
 Happiness Rank                   79.493671
Happiness Score                   5.375734
Standard Error                    0.047885
Economy (GDP per Capita)          0.846137
Family                            0.991046
Health (Life Expectancy)          0.630259
Freedom                           0.428615
Trust (Government Corruption)     0.143422
Generosity                        0.237296
Dystopia Residual                 2.098977
dtype: float64


In [46]:
print("\nMean:\n",new_data.mode())


Mean:
      Happiness Rank  Happiness Score  Standard Error  \
0              82.0            5.192         0.03751   
1               NaN              NaN         0.03780   
2               NaN              NaN         0.04394   
3               NaN              NaN         0.04934   
4               NaN              NaN         0.05051   
..              ...              ...             ...   
153             NaN              NaN             NaN   
154             NaN              NaN             NaN   
155             NaN              NaN             NaN   
156             NaN              NaN             NaN   
157             NaN              NaN             NaN   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     0.00000  0.00000                   0.92356  0.00000   
1                     0.01530  0.13995                       NaN  0.07699   
2                     0.01604  0.30285                       NaN  0.09245   
3          

In [47]:
print("\nMean:\n",new_data.median())


Mean:
 Happiness Rank                   79.500000
Happiness Score                   5.232500
Standard Error                    0.043940
Economy (GDP per Capita)          0.910245
Family                            1.029510
Health (Life Expectancy)          0.696705
Freedom                           0.435515
Trust (Government Corruption)     0.107220
Generosity                        0.216130
Dystopia Residual                 2.095415
dtype: float64


In [48]:
from numpy import cov

In [49]:
data1= data.Family
data2 = data.Freedom
data1
data2

0      0.66557
1      0.62877
2      0.64938
3      0.66973
4      0.63297
        ...   
153    0.59201
154    0.48450
155    0.15684
156    0.11850
157    0.36453
Name: Freedom, Length: 158, dtype: float64

In [50]:
covariance=cov(data1,data2)
print(covariance)

[[0.07418492 0.0181217 ]
 [0.0181217  0.02270832]]


In [51]:
from scipy.stats import pearsonr
data1=data.Family
data2=data.Freedom
corr,_=pearsonr(data1,data2)
print(corr)

0.44151821062286056


In [71]:
from scipy.stats import spearmanr
data1=data.Family
data2=data.Freedom
corr,_=spearmanr(data1,data2)
print(corr)

0.5281391142435108


## Data2

In [53]:
import pandas as pd
data2=pd.read_csv(r"C:\Users\kyathi\Downloads\4_Drug200.csv")
data2


Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [54]:
print(data2.sum())


Age                                                         8863
Sex            FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...
BP             HIGHLOWLOWNORMALLOWNORMALNORMALLOWNORMALLOWLOW...
Cholesterol    HIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHNORMALHIGH...
Na_to_K                                                 3216.897
Drug           drugYdrugCdrugCdrugXdrugYdrugXdrugYdrugCdrugYd...
dtype: object


In [55]:
print(data2.cumsum())


      Age                                                Sex  \
0      23                                                  F   
1      70                                                 FM   
2     117                                                FMM   
3     145                                               FMMF   
4     206                                              FMMFF   
..    ...                                                ...   
195  8732  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
196  8748  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
197  8800  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
198  8823  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   
199  8863  FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...   

                                                    BP  \
0                                                 HIGH   
1                                              HIGHLOW   
2                                           HIGHLOWLOW   

In [56]:
print(data2.count())

Age            200
Sex            200
BP             200
Cholesterol    200
Na_to_K        200
Drug           200
dtype: int64


In [57]:
print(data2.min())

Age               15
Sex                F
BP              HIGH
Cholesterol     HIGH
Na_to_K        6.269
Drug           drugA
dtype: object


In [58]:
print(data2.max())


Age                74
Sex                 M
BP             NORMAL
Cholesterol    NORMAL
Na_to_K        38.247
Drug            drugY
dtype: object


In [59]:
BP = {"BP":{"LOW":0,"NORMAL":1,"HIGH":2}}
data2 = data2.replace(BP)
Cholesterol = {"Cholesterol":{"LOW":0,"NORMAL":1,"HIGH":2}}
data2 = data2.replace(Cholesterol)
data2


Age Sex  BP  Cholesterol  Na_to_K   Drug
0     23   F   2            2   25.355  drugY
1     47   M   0            2   13.093  drugC
2     47   M   0            2   10.114  drugC
3     28   F   1            2    7.798  drugX
4     61   F   0            2   18.043  drugY
..   ...  ..  ..          ...      ...    ...
195   56   F   0            2   11.567  drugC
196   16   M   0            2   12.006  drugC
197   52   M   1            2    9.894  drugX
198   23   M   1            1   14.020  drugX
199   40   F   0            1   11.349  drugX

[200 rows x 6 columns]

In [60]:
new_data2 = data2.drop(["Drug","Sex"],axis=1)

In [61]:
print(new_data2.mean())

Age            44.315000
BP              1.065000
Cholesterol     1.515000
Na_to_K        16.084485
dtype: float64


In [62]:
print(new_data2.mode())


    Age   BP  Cholesterol  Na_to_K
0  47.0  2.0          2.0   12.006
1   NaN  NaN          NaN   18.295


In [63]:
print(new_data2.median())

Age            45.0000
BP              1.0000
Cholesterol     2.0000
Na_to_K        13.9365
dtype: float64


In [64]:
print(new_data2.describe())

              Age          BP  Cholesterol     Na_to_K
count  200.000000  200.000000   200.000000  200.000000
mean    44.315000    1.065000     1.515000   16.084485
std     16.544315    0.839224     0.501029    7.223956
min     15.000000    0.000000     1.000000    6.269000
25%     31.000000    0.000000     1.000000   10.445500
50%     45.000000    1.000000     2.000000   13.936500
75%     58.000000    2.000000     2.000000   19.380000
max     74.000000    2.000000     2.000000   38.247000


In [65]:
from numpy import cov

In [66]:
data3=data2.Age
data4=data2.Cholesterol
print(data3)
print(data4)

0      23
1      47
2      47
3      28
4      61
       ..
195    56
196    16
197    52
198    23
199    40
Name: Age, Length: 200, dtype: int64
0      2
1      2
2      2
3      2
4      2
      ..
195    2
196    2
197    2
198    1
199    1
Name: Cholesterol, Length: 200, dtype: int64


In [67]:
covariance=cov(data3,data4)
print(covariance)


[[2.73714347e+02 5.65603015e-01]
 [5.65603015e-01 2.51030151e-01]]


In [68]:
from scipy.stats import pearsonr
data3=data2.Age
data4=data2.Cholesterol
corr,_=pearsonr(data3,data4)
print(corr)

0.06823386810675444


In [69]:
from scipy.stats import spearmanr
data3=data2.Age
data4=data2.Cholesterol
corr,_=spearmanr(data3,data4)
print(corr)

0.0688114033967977
